site_name: Archery
theme: material
pages:
- 'Overview': 'index.md'
- 'Getting started': 'install.md'
- 'Setting up the Environment': 'setupGuide.md'
#- Usage: 'Usage.md'
- Contributors: 'contributors.md'
- Roadmap: 'roadmap.md'

# Options
extra:
  feature:
    tabs: true
  palette:
    primary: indigo
    accent: indigo
  social:
    - type: github-alt
      link: https://github.com/anandtiwarics/archerysec
    - type: twitter
      link: https://twitter.com/archerysec
    - type: facebook
      link: https://twitter.com/archerysec

# Project information
site_name: Archery
site_description: All about ArcherySec.
site_author: Anand Tiwari
site_url: https://anandtiwarics.github.io/archerysec

# Repository
repo_name: anandtiwarics/archerysec
repo_url: https://github.com/anandtiwarics/archerysec