site_name: Archery
theme: material
pages:
- 'Overview': 'index.md'
- 'Installation': 'install.md'
- 'Setting up the Environment': 'setupGuide.md'
- Usage: 'Usage.md'
- Contributors: 'contributors.md'
- Roadmap: 'roadmap.md'